### ISSUE TITLE
Version epub

### ISSUE THREAD

**Issue by samueltardieu** [Sabin-Teyssier/dp#1]
Une version epub serait-elle disponible ?

**Comment by Sabin-Teyssier** [comment]
Bonjour !
Pas encore - mais c'est une bonne idée, je vais en préparer une (juste, ça ne va pas être possible avant une dizaine de jours).

**Comment by Sabin-Teyssier** [comment]
Ça y est, elle est disponible :
https://github.com/Sabin-Teyssier/dp/blob/master/Les_dessous_de_paillasse.epub
Désolé pour le délai !
